version: '3'

services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: "./backend"
    networks:
      - sochat
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    container_name: db
    image: 'postgres:13'
    env_file:
      - .env
    networks:
      - sochat
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - sochat
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
  ssh-client:
    build:
      context: ./ssh-client
      dockerfile: Dockerfile
    networks:
      - sochat
    ports:
      - "2222:22"
    volumes:
      - ./ssh-client:/app
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - sochat
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:

networks:
  sochat:
    driver: bridge
